kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: my-cluster2
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001
        hostPort: 30001
  - role: worker
  - role: worker  
