apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-affinity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - frontend
      containers:
        - name: nginx
          image: nginx:latest
