apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: busybox
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

metadata:
  name:nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: 
      initContainers:
      - name: init-for-sql
        image: busybox
        command: ['sh', '-c', 'echo Initializing SQL Server...; sleep 10; echo SQL Server Initialized.']  
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80          